//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiseAdmin.WiseHelp {
    
    
    public partial class frmChamadosAbertos {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WiseAdmin.WiseHelp.WiseHelp Master {
            get {
                return ((WiseAdmin.WiseHelp.WiseHelp)(base.Master));
            }
        }
    }
}
